# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - nodePort: 30500
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
