apiVersion: v1
kind: Service
metadata:
  name: mqtt-client
spec:
  type: ClusterIP  # Use NodePort or LoadBalancer if you need external access
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: mqtt-client

