apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-client
  labels:
    app: opcua-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcua-client
  template:
    metadata:
      labels:
        app: opcua-client
    spec:
      containers:
      - name: cesmiiopcuaclient
        image: <REPLACE>/cesmiiopcuaclient
        env:
          - name: OPCUA_SERVER_URL
            value: "opc.tcp://192.168.1.3:4840/freeopcua/server/"     
        ports:
          - containerPort: 4840
        command: ["python"]
        args: ["cesmiiopcuaclient.py", "$(OPCUA_SERVER_URL)"]

