apiVersion: apps/v1
kind: Deployment
metadata:
  name: cesmiiopcuagraphql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cesmiiopcuagraphql-app
  template:
    metadata:
      labels:
        app: cesmiiopcuagraphql-app
    spec:
      containers:
      - name: cesmiiopcuagraphql
        image: <REPLACE>/cesmiiopcuagraphql:latest
        args:
        - --authenticator
        - $(AUTHENTICATOR)
        - --password
        - $(PASSWORD)
        - --name
        - $(NAME)
        - --role
        - $(ROLE)
        - --graphurl 
        - $(URL)
        - --ids
        - "<REPLACE>"
        - "<REPLACE>"
        - "<REPLACE>"
        - --opcurl
        - $(OPCUA_URL) 
        env:
        - name: AUTHENTICATOR
          value: "<REPLACE>"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: NAME
          value: "<REPLACE>
        - name: ROLE
          value: "<REPLACE>"
        - name: URL
          value: "<REPLACE>"
        - name: OPCUA_URL
          value: "opc.tcp://192.168.1.3:4840/freeopcua/server/"
        ports:
        - containerPort: 4840  

